apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicebusexporter.fullname" . }}
  labels:
{{ include "servicebusexporter.labels" . | indent 4 }}
data:
  connectionString: {{ .Values.connectionString | b64enc }}
