{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "servicebusexporter.serviceAccountName" . }}
  labels:
{{ include "servicebusexporter.labels" . | indent 4 }}
{{- end -}}
